fint:
  kafka:
    application-id: fagprove-elev-consumer
    enable-ssl: false
    default-replicas: 1
    topic:
      org-id: fintlabs.no
      domain-context: fagprove


spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fagprove-elev-consumer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mvc:
#    servlet:
#      path: /elev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/ui